### PR TITLE
Quipu compiled on Ubuntu

### PR DESCRIPTION
**Pull request by zosrothko**
Hello
This is my answer to the BountySource issue: https://app.bountysource.com/issues/109508245-will-not-compile-on-a-modern-linux-system-bounty

### CODE REVIEW

**Comment by JonathanWilbur** [comment]
The command `./make everything` seems to succeed, but `./make inst-everything` fails in a fresh new `ubuntu` Docker image. Specifically, I get a lot of `No such file or directory` errors. Here is a snippet of the errors I get:

```
make[2]: Entering directory '/isode-8.0/quipu'
cp /usr/local/sbin/ros.quipu zros.quipu
rm -f /usr/local/sbin/ros.quipu
cp xquipu /usr/local/sbin/ros.quipu
4608 -rwxr-xr-x 1 root 4717208 Jun 30 15:38 /usr/local/sbin/ros.quipu

install -m 0644 -c /tmp/quipu.8c /usr/local/share/man/man8/quipu.8c
install: cannot create regular file '/usr/local/share/man/man8/quipu.8c': No such file or directory
install -m 0644 -c /tmp/quiputailor.5 /usr/local/share/man/man5/quiputailor.5
install: cannot create regular file '/usr/local/share/man/man5/quiputailor.5': No such file or directory

cd dish; ./make DESTDIR= -kw -k inst-all
make[3]: Entering directory '/isode-8.0/quipu/dish'
cp /usr/local/bin/dish zxdish
cp: cannot stat '/usr/local/bin/dish': No such file or directory
make[3]: *** [Makefile:74: /usr/local/bin/dish] Error 1
cp libdish.a /usr/local/lib/libdish.a
ranlib /usr/local/lib/libdish.a
../../util/make-lib.sh: 33: cd: can't cd to /usr/tmp
936 -rw-r--r-- 1 root 956622 Jun 30 15:38 /usr/local/lib/libdish.a

install -m 0644 -c /tmp/dish.1c /usr/local/share/man/man1/dish.1c
install: cannot create regular file '/usr/local/share/man/man1/dish.1c': No such file or directory

make[3]: Target 'inst-all' not remade because of errors.
make[3]: Leaving directory '/isode-8.0/quipu/dish'
make[2]: *** [Makefile:200: sub-inst-all] Error 2
make[2]: Target 'inst-all' not remade because of errors.
make[2]: Leaving directory '/isode-8.0/quipu'
make[1]: *** [Makefile:224: inst-quipu] Error 2
make[1]: Leaving directory '/isode-8.0'
make: *** [Makefile:115: inst-everything] Error 2
```

I even installed `man-db` and `manpages` to make sure this was not an issue with `man` not being present, and that did not work. Please test this on an `ubuntu` Docker image, which you can do by running `docker run -it ubuntu /bin/bash`. That will make your build repeatable.

Also, it is a stipulation of the bounty that all sub-targets of `make everything` build successfully. I will not accept just Quipu. I don't just want Quipu for integration testing: I want to preserve the ISODE project.

**Comment by zosrothko** [comment]
@JonathanWilbur This PR makes the job as described in the bounty (except the last make that should run as root)
```
cp config/linux h/config.h
% cp config/linux.make config/CONFIG.make
% cp config/*.local support/
% ./make everything
# sudo ./make inst-everything
```

**Comment by JonathanWilbur** [comment]
I can see that you just copied all of @abcpro1 's commits in an attempt to claim the bounty that he put the work in for. Closing.

**Comment by zosrothko** [comment]
@JonathanWilbur I made all fixes year's ago to all basic modules as support, tsap, ssap, acsap, pepy, rosap, and pepsy. This guy @abcpro1 has taken all my fixes. So I do not see why I could not take his fixes. You state it was a race... that's the race

**Pull request closed without merging**
