### PR TITLE
Compile on Ubuntu 22

### PR DESCRIPTION
**Pull request by bl00mber**
```shell
apt update
apt install -y build-essential git bison flex
git clone https://github.com/bl00mber/isode-8.0.git
cd isode-8.0
./make cp-files
./make everything
./make inst-everything
```

### CODE REVIEW

**Comment by JonathanWilbur** [comment]
When I attempt to build this in a brand new `ubuntu` Docker image, it fails to run your `cp-files` make target. I like that extra automation you did, but that build step does not work from a new image. It only works if you already copied those files over (lol). I can't remember the error because it scrolled out of view, but I believe it was `No recipe to make target config/CONFIG.make`. No problem, though. I see what you were attempting here and just manually copied the files.

However, when I run `./make everything`, I get these errors:

```
In file included from ftp.c:46:
ftp_var.h:86:14: error: conflicting types for 'sys_errlist'
   86 | extern char *sys_errlist[];
      |              ^~~~~~~~~~~
In file included from /usr/include/stdio.h:781,
                 from /usr/include/malloc.h:24,
                 from ../h/general.h:154,
                 from ftp.c:30:
/usr/include/x86_64-linux-gnu/bits/sys_errlist.h:27:26: note: previous declaration of 'sys_errlist' was here
   27 | extern const char *const sys_errlist[];
      |                          ^~~~~~~~~~~
ftp.c:79:7: error: conflicting types for 'sys_errlist'
   79 | char *sys_errlist[];
      |       ^~~~~~~~~~~
In file included from /usr/include/stdio.h:781,
                 from /usr/include/malloc.h:24,
                 from ../h/general.h:154,
                 from ftp.c:30:
/usr/include/x86_64-linux-gnu/bits/sys_errlist.h:27:26: note: previous declaration of 'sys_errlist' was here
   27 | extern const char *const sys_errlist[];
      |                          ^~~~~~~~~~~
make[2]: *** [Makefile:37: ftp.o] Error 1
cc -w -g -I. -I../h -DPEPYPATH   -DBRIDGE -I../ftam2/ -c ftp_lib.c
In file included from ftp_lib.c:42:
ftp_var.h:86:14: error: conflicting types for 'sys_errlist'
   86 | extern char *sys_errlist[];
      |              ^~~~~~~~~~~
In file included from /usr/include/stdio.h:781,
                 from ftp_lib.c:38:
/usr/include/x86_64-linux-gnu/bits/sys_errlist.h:27:26: note: previous declaration of 'sys_errlist' was here
   27 | extern const char *const sys_errlist[];
      |                          ^~~~~~~~~~~
make[2]: *** [Makefile:37: ftp_lib.o] Error 1
make[2]: Target 'all' not remade because of errors.
make[2]: Leaving directory '/isode-8.0/ftam-ftp'
cd ftp-ftam; ./make DESTDIR= -w -k all
make[2]: Entering directory '/isode-8.0/ftp-ftam'
Makefile:37: warning: overriding recipe for target '.c.o'
../config/CONFIG.make:112: warning: ignoring old recipe for target '.c.o'
cc -w -g -I. -I../h -DPEPYPATH   -DBRIDGE -I../ftam2/ -c ftpd.c
ftpd.c:81:7: error: conflicting types for 'sys_errlist'
   81 | char *sys_errlist[];
      |       ^~~~~~~~~~~
In file included from /usr/include/stdio.h:781,
                 from /usr/include/malloc.h:24,
                 from ../h/general.h:154,
                 from ../h/sys.file.h:26,
                 from ftpd.c:45:
/usr/include/x86_64-linux-gnu/bits/sys_errlist.h:27:26: note: previous declaration of 'sys_errlist' was here
   27 | extern const char *const sys_errlist[];
      |                          ^~~~~~~~~~~
make[2]: *** [Makefile:37: ftpd.o] Error 1
```

Please test the build on a brand new `ubuntu` Docker image so I can recreate the build. You can do this by running `docker run -it /bin/bash` (assuming you have Docker installed). Also, I tried building this on my bare metal machine with no success either.

**Comment by bl00mber** [comment]
@JonathanWilbur
Which docker version are you using?
`docker --version` Docker version 20.10.17
`cat /etc/os-release` Ubuntu 22.04
`uname -r` 5.15.0-23-generic
I modified code according to error you are getting (I myself not getting it inside of docker)

**Comment by JonathanWilbur** [comment]
Still getting this error when running the `cp-files` target:

```
make: config/CONFIG.make: No such file or directory
make: *** No rule to make target 'config/CONFIG.make'.  Stop.
```

But this isn't a deal breaker. Just letting you know. Still testing.

**Comment by bl00mber** [comment]
I committed sec ago you'll probably fail vt lib

**Comment by JonathanWilbur** [comment]
Versions:

```
Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
5.14.0-1044-oem
```

**Comment by JonathanWilbur** [comment]
```
./xsnmpi -f objects.defs compile -s loadobjects
make[2]: ./xsnmpi: No such file or directory
make[2]: *** [Makefile:426: loadobjects.c] Error 127

```

**Comment by bl00mber** [comment]
It is a circular dependency. For some reason it builds on my environment. I'll fix it if selected between those two PR's, for now I just added compiled binary to commit. That binary will rebuild after being used.

**Pull request closed without merging**
